name: Veracode Scan

on:
  repository_dispatch:
    types: [register-build-example-two]

env:
  ARTIFACT_NAME: artifact-build
  ARTIFACT_PATH: verascan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Veracode Package
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          ((New-Object System.Net.WebClient).DownloadString('https://tools.veracode.com/veracode-cli/install')) | sh
          Move-Item -Path veracode -Destination '/usr/local/bin/veracode' -Force
          $command = 'veracode'
          $veracodeExecutable = (Get-Command -Name $command).Path

          $arguments = @("package", "--source", ".", "--output", "$env:ARTIFACT_PATH", "--trust")
          & $veracodeExecutable @arguments

          $artifacts = Get-ChildItem -Recurse -File -Path "$env:ARTIFACT_PATH" | Where-Object { $_.Extension -in '.war','.jar','.zip' } | Select-Object -ExpandProperty FullName
          if ($null -eq $artifacts) {
            Write-Host "##vso[task.logissue type=error]No packaged artifacts found"
            exit 1
          }

          Write-Host "Artifacts found:"
          $artifacts | Format-Table FullName, Length -AutoSize -HideTableHeaders
          
          Write-Host "Total artifacts: $($artifacts.Count)"  

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
          retention-days: 3

  register:
    runs-on: ${{ fromJSON(github.event.client_payload.user_config.default_runs_on) }}
    name: register
    needs: [ build ]
    steps:
    - name: Register build
      id: register-build
      uses: veracode/github-actions-integration-helper@v0.1.10
      with:
        action: registerBuild
        token: ${{ github.event.client_payload.token }}
        appname: "test-verademo-dotnet-1"
        source_repository: ${{ github.event.client_payload.repository.full_name }}
        check_run_id: ${{ github.run_id }}
        check_run_name: ${{ github.workflow }}
        head_sha: ${{ github.event.client_payload.sha }}
        event_type: ${{ github.event.client_payload.event_type }}
        branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
        issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}
